services:
  prefect-server:
    image: prefecthq/prefect:2.10.3-python3.9
    container_name: prefect-server
    command: server start --port 4200
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://localhost:4200

  ml-pipeline:
    build:
      context: .
    container_name: ml-pipeline
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200
    volumes:
      - .:/app
